CREATE DATABASE EBM_DB

use EBM_DB

CREATE TABLE TB_CLIENTE 
(
    ID_CLIENTE INT PRIMARY KEY NOT NULL,
    NM_CLIENTE VARCHAR(250) NOT NULL, 
    CNPJ CHAR(14) NOT NULL, 
    END_CLIENTE VARCHAR(200) NOT NULL, 
    CONTATO_CLIENTE CHAR(25) NOT NULL,
    OBS VARCHAR(500) 
)

CREATE TABLE TB_MATERIAIS
(
    ID_MATERIAL INT PRIMARY KEY NOT NULL, 
    DESC_MATERIAL VARCHAR (200) NOT NULL, 
    ESTOQUE INT NOT NULL, 
    OBS VARCHAR(500)
)

CREATE TABLE TB_CONTRATO
(
    ID_CONTRATO INT PRIMARY KEY NOT NULL, 
    ID_CLIENTE INT FOREIGN KEY REFERENCES TB_CLIENTE(ID_CLIENTE),     
    MATERIAIS VARCHAR(7000) NOT NULL, 
    VL_CONTRATO MONEY NOT NULL, 
    DT_FECHAMENTO DATE NOT NULL, 
    DT_VENCIMENTO DATE NOT NULL, 
    OBS VARCHAR (500)
)

CREATE TABLE TB_OBRA
(
    ID_OBRA INT PRIMARY KEY NOT NULL, 
    ID_CONTRATO INT FOREIGN KEY REFERENCES TB_CONTRATO(ID_CONTRATO),
    END_OBRA VARCHAR(200) NOT NULL, 
    CONTATO_OBRA CHAR(25) NOT NULL,
    OBS VARCHAR(500)
)

CREATE TABLE TB_REQUISICAO
(
    ID_REQUISICAO INT PRIMARY KEY NOT NULL, 
    ID_OBRA INT FOREIGN KEY REFERENCES TB_OBRA(ID_OBRA),
    ID_MATERIAL INT FOREIGN KEY REFERENCES TB_MATERIAIS(ID_MATERIAL), 
    QTD_MATERIAIS INT NOT NULL,
    DT_ABERT DATE NOT NULL, 
    DT_FECHAMENTO DATE NOT NULL,
    OBS VARCHAR(500) 
)

CREATE TABLE TB_COMPRA
(
    ID_COMPRA INT PRIMARY KEY NOT NULL, 
    ID_REQUISICAO INT FOREIGN KEY REFERENCES TB_REQUISICAO(ID_REQUISICAO),
    DT_COMPRA DATE NOT NULL, 
    VL_COMPRA MONEY NOT NULL, 
    NF_COMPRA VARCHAR(20) NOT NULL, 
    OBS VARCHAR(500)
)